export default {
	BACKEND_URL: "http://192.168.1.11:3000",
	GIVEAWAY_TYPES: {
		FOOD: "FOOD",
		CLOTHES: "CLOTHES",
		FURNITURE: "FURNITURE"
	},
	AMMOUNT_TYPES: {
		ITEMS: "ITEMS",
		KG: "KG",
		LITRE: "LITRE",
		PORTIONS: "PORTIONS"
	}
};
